### ISSUE TITLE
Using require instead of import fullPageScreenshot is not a function

### ISSUE THREAD

**Issue by mvaneijgen** [morteza-fsh/puppeteer-full-page-screenshot#5]
I thought i had fixed my fullscreen screenshot issue with a `clip:` on the screenshot function, but for some reason everything below the fold is now white with this setting 

```
const bodyHandle = await page.$("body");
const { width, height } = await bodyHandle.boundingBox();
await page.screenshot({
  path: deviceDirectory + imageName,
  // fullPage: true,
  clip: {
    x: 0,
    y: 0,
    width,
    height,
  },
});
```

This made me to set out and try and fix the issue account and found your plugin. I'm doing something weird which means I can't use `import` and have to use `const fullPageScreenshot = require("puppeteer-full-page-screenshot");`, but this will result in an error `TypeError: fullPageScreenshot is not a function` 

Is there a way to make this work? 

[My full script can be found here `puppeteer-testing.js`](https://github.com/mvaneijgen/screenshot-generator-app/blob/master/src/renderer/plugins/puppeteer-testing.js)

**Comment by morteza-fsh** [comment]
Babel 6+ does not add CommonJS default export anymore, you can use `.default` like:
```javascript
const fullPageScreenshot = require("puppeteer-full-page-screenshot").default;
// or
const {default: fullPageScreenshot} = require("puppeteer-full-page-screenshot");
```

**Comment by mvaneijgen** [comment]
Thanks that works great! Now I'll be finding a way to remove fixed elements and I'll be golden. Thanks again

**Comment by morteza-fsh** [comment]
You're welcome,
This thread may help you: https://github.com/morteza-fsh/puppeteer-full-page-screenshot/issues/4
