### ISSUE TITLE
Device pixel ratio not considered resulting in wrongly cropped screenshot

### ISSUE THREAD

**Issue by 3dom-design** [morteza-fsh/puppeteer-full-page-screenshot#6]
When the device has a pixel ratio different from 1, the last / bottom screenshot is cropped at wrong offset / size before stitching, resulting in mangled bottom area of the screenshot.

Here is the result for an iPhone SE (scale factor of 2) with a red overlay on the `image.crop()` area:

![iPhoneSE_0_home_bottom](https://user-images.githubusercontent.com/66597137/84010663-a7d54700-a97d-11ea-97cc-b8790cb3c33b.png)

Pull request coming! =)

**Comment by morteza-fsh** [comment]
Thanks,
I just merged the PR
